Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # specific for ubuntu1
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.provision "ansible_local", playbook: "ubuntu.yml"
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.network "private_network", ip: "192.168.56.101"
  end
  # specific for ubuntu2
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/focal64"
    ubuntu2.vm.provision "ansible_local", playbook: "ubuntu.yml"
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.network "private_network", ip: "192.168.56.102"
  end

  # specific for rocky
  config.vm.define "rocky" do |rocky|
    rocky.vm.box = "rockylinux/9"
    rocky.vm.hostname = "rocky"
    rocky.vm.network "private_network", ip: "192.168.56.103"
  end
end