#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Recovery' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-35aea923-d4d6-418f-b28c-b4a0e368d31a' {
        recordfail
        load_video
        gfxmode $linux_gfx_mode
        insmod gzio
        if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_msdos
        insmod ext2
        set root='hd0,msdos1'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1  35aea923-d4d6-418f-b28c-b4a0e368d31a
        else
          search --no-floppy --fs-uuid --set=root 35aea923-d4d6-418f-b28c-b4a0e368d31a
        fi
        linux   /boot/vmlinuz-5.4.0-124-generic root=UUID=35aea923-d4d6-418f-b28c-b4a0e368d31a rw init=/bin/bash
        initrd  /boot/initrd.img-5.4.0-124-generic
}